# Generated by Django 3.1.3 on 2020-11-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_path', models.CharField(max_length=200)),
                ('character', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.IntegerField()),
                ('adult', models.BooleanField()),
                ('poster_path', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('nation', models.CharField(max_length=50)),
                ('vote_average', models.FloatField()),
                ('comment_score_sum', models.IntegerField(default=0)),
                ('comment_score_average', models.FloatField(default=0)),
                ('release_date', models.DateField()),
                ('video_path', models.CharField(max_length=200)),
                ('actors', models.ManyToManyField(blank=True, related_name='movies', to='movies.Actor')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.Genre')),
            ],
        ),
    ]
